version: 2.1
orbs: 
  python: circleci/python@2.0.3
jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pip-dependency-file: requirements.txt
          pkg-manager: pip
      - run:
          command: |
            pipenv run python manage.py test
      - store_test_results: 
          path: test-results
      - store_artifacts:
          path: test-results
          destination: tr1
  
  build-and-push:
   machine: true
   steps:
     - checkout
     - run: |
         echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
     - run: docker build -t motzi/reefmonitor:$CIRCLE_BRANCH .
     - run: docker push motzi/reefmonitor:$CIRCLE_BRANCH

  build-and-push-tagged:
   machine: true
   steps:
     - checkout
     - run: |
         echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
     - run: docker build -t motzi/reefmonitor:$CIRCLE_TAG .
     - run: docker push motzi/reefmonitor:$CIRCLE_TAG
     
  
workflows:
  release: 
    jobs:
      - build-and-test:
          filters:
            tags:
              only: /.*/
      - build-and-push:
          requires:
            - build-and-test
          filters:
            branches:
              only: /.*/
            tags:
              ignore: /.*/
      - build-and-push-tagged:
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
          requires:
            - build-and-test