version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10.1
    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            sudo pip install pipenv
            pipenv install
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          command: |
            pipenv run python manage.py test
      - store_test_results: 
          path: test-results
      - store_artifacts:
          path: test-results
          destination: tr1
  
  build-and-push:
   machine: true
   steps:
     - checkout
     - run: |
         echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
     - run: docker build -t motzi/reefmonitor:$CIRCLE_BRANCH .
     - run: docker push motzi/reefmonitor:$CIRCLE_BRANCH

  build-and-push-tagged:
   machine: true
   steps:
     - checkout
     - run: |
         echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
     - run: docker build -t motzi/reefmonitor:$CIRCLE_TAG .
     - run: docker push motzi/reefmonitor:$CIRCLE_TAG
     
  
workflows:
  release: 
    jobs:
      - build-and-test:
          filters:
            tags:
              only: /.*/
      - build-and-push:
          requires:
            - build-and-test
          filters:
            branches:
              only: /.*/
            tags:
              ignore: /.*/
      - build-and-push-tagged:
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
          requires:
            - build-and-test