# Generated by Django 3.2.9 on 2022-01-02 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquariums', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('salinity', 'Sali'), ('temperature', 'Temp'), ('carbonate', 'Carb'), ('calcium', 'Calc'), ('magnesium', 'Magn')], default='temperature', max_length=48)),
                ('value', models.FloatField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='aquarium',
            options={'verbose_name': 'Aquarium', 'verbose_name_plural': 'Aquariums'},
        ),
        migrations.AlterField(
            model_name='aquarium',
            name='name',
            field=models.CharField(max_length=24),
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='timestamp')),
                ('parameters', models.ManyToManyField(to='aquariums.Parameter')),
            ],
        ),
    ]
