# Generated by Django 3.2.9 on 2022-01-10 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquariums', '0004_alter_parameter_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='name',
            field=models.CharField(choices=[('salinity', 'Salinity'), ('temperature', 'Temperature'), ('carbonate', 'Carbonate Hardness'), ('calcium', 'Calcium'), ('magnesium', 'Magnesium')], default='temperature', max_length=48),
        ),
    ]
