# Generated by Django 3.2.9 on 2022-01-12 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquariums', '0006_alter_parameter_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='name',
            field=models.CharField(choices=[('Salinity', 'Salinity'), ('Temperature', 'Temperature'), ('Carbonate Hardness', 'Carbonate Hardness'), ('Calcium', 'Calcium'), ('Magnesium', 'Magnesium')], default='Temperature', max_length=48),
        ),
    ]
