# Generated by Django 3.2.9 on 2022-01-15 10:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rules', '0001_initial'),
        ('aquariums', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timeout',
            fields=[
                ('id', models.CharField(blank=True, default=uuid.uuid4, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('start', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('aquarium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aquariums.aquarium')),
                ('violations', models.ManyToManyField(to='rules.Violation')),
            ],
        ),
    ]
