# Generated by Django 3.2.9 on 2022-01-15 10:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aquariums', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hint',
            fields=[
                ('id', models.CharField(blank=True, default=uuid.uuid4, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('parameter', models.CharField(choices=[('Salinity', 'Salinity'), ('Temperature', 'Temperature'), ('Carbonate Hardness', 'Carbonate Hardness'), ('Calcium', 'Calcium'), ('Magnesium', 'Magnesium')], max_length=48)),
                ('type', models.CharField(choices=[('Minimum', 'Minimum'), ('Maximum', 'Maximum')], max_length=48)),
                ('message', models.CharField(max_length=4096)),
            ],
            options={
                'verbose_name': 'Hint',
                'verbose_name_plural': 'Hints',
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.CharField(blank=True, default=uuid.uuid4, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('value', models.FloatField()),
                ('type', models.CharField(choices=[('Minimum', 'Minimum'), ('Maximum', 'Maximum')], default='Minimum', max_length=48)),
                ('parameter', models.CharField(choices=[('Salinity', 'Salinity'), ('Temperature', 'Temperature'), ('Carbonate Hardness', 'Carbonate Hardness'), ('Calcium', 'Calcium'), ('Magnesium', 'Magnesium')], default='Temperature', max_length=48)),
                ('aquarium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aquariums.aquarium')),
            ],
            options={
                'verbose_name': 'Rule',
                'verbose_name_plural': 'Rules',
            },
        ),
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.CharField(blank=True, default=uuid.uuid4, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('timestamp', models.DateTimeField()),
                ('value', models.FloatField()),
                ('aquarium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aquariums.aquarium')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rules.rule')),
            ],
            options={
                'verbose_name': 'Violation',
                'verbose_name_plural': 'Violations',
            },
        ),
    ]
