# Generated by Django 3.2.9 on 2022-01-04 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aquariums', '0003_auto_20220104_1549'),
        ('rules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='parameter',
            field=models.CharField(choices=[('Salinity', 'Sali'), ('Temperature', 'Temp'), ('Carbonate Hardness', 'Carb'), ('Calcium', 'Calc'), ('Magnesium', 'Magn')], default='Temperature', max_length=48),
        ),
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('value', models.FloatField()),
                ('aquarium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aquariums.aquarium')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rules.rule')),
            ],
            options={
                'verbose_name': 'Violation',
                'verbose_name_plural': 'Violations',
            },
        ),
    ]
