# Generated by Django 3.2.9 on 2022-01-04 16:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0002_auto_20220104_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='violation',
            name='id',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
