# Generated by Django 3.2.9 on 2022-01-04 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0003_alter_violation_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='violation',
            options={'ordering': ('-timestamp',), 'verbose_name': 'Violation', 'verbose_name_plural': 'Violations'},
        ),
    ]
