# Generated by Django 3.2.9 on 2022-01-06 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0005_alter_violation_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='parameter',
            field=models.CharField(choices=[('Salinity', 'Salinity'), ('Temperature', 'Temperature'), ('Carbonate Hardness', 'Carbonate Hardness'), ('Calcium', 'Calcium'), ('Magnesium', 'Magnesium')], default='Temperature', max_length=48),
        ),
        migrations.AlterField(
            model_name='rule',
            name='type',
            field=models.CharField(choices=[('Minimum', 'Minimum'), ('Maximum', 'Maximum')], default='Minimum', max_length=48),
        ),
    ]
