# Generated by Django 3.2.9 on 2022-01-10 18:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0006_auto_20220106_2219'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hint',
            fields=[
                ('id', models.CharField(blank=True, default=uuid.uuid4, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('parameter', models.CharField(choices=[('salinity', 'Salinity'), ('temperature', 'Temperature'), ('carbonate', 'Carbonate Hardness'), ('calcium', 'Calcium'), ('magnesium', 'Magnesium')], max_length=48)),
                ('type', models.CharField(choices=[('Minimum', 'Minimum'), ('Maximum', 'Maximum')], max_length=48)),
                ('hint', models.CharField(max_length=4096)),
            ],
            options={
                'verbose_name': 'Hint',
                'verbose_name_plural': 'Hints',
            },
        ),
        migrations.AlterField(
            model_name='rule',
            name='parameter',
            field=models.CharField(choices=[('salinity', 'Salinity'), ('temperature', 'Temperature'), ('carbonate', 'Carbonate Hardness'), ('calcium', 'Calcium'), ('magnesium', 'Magnesium')], default='temperature', max_length=48),
        ),
    ]
