# Generated by Django 3.2.9 on 2022-01-10 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0007_auto_20220110_1954'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hint',
            old_name='hint',
            new_name='message',
        ),
    ]
