# Generated by Django 3.2.9 on 2022-01-12 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0008_rename_hint_hint_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hint',
            name='parameter',
            field=models.CharField(choices=[('Salinity', 'Sali'), ('Temperature', 'Temp'), ('Carbonate Hardness', 'Carb'), ('Calcium', 'Calc'), ('Magnesium', 'Magn')], max_length=48),
        ),
        migrations.AlterField(
            model_name='rule',
            name='parameter',
            field=models.CharField(choices=[('Salinity', 'Sali'), ('Temperature', 'Temp'), ('Carbonate Hardness', 'Carb'), ('Calcium', 'Calc'), ('Magnesium', 'Magn')], default='Temperature', max_length=48),
        ),
    ]
